version: "3"
services:
    mysql57:
        image: mysql:5.7
        dns_search: gha.local
        hostname: mysql57.gha.local
        domainname: gha.local
        restart: on-failure:2
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-upublic", "-ppublic"]
            interval: 120s
            timeout: 1s
            retries: 3
        networks:
            gha:
                aliases:
                    - mysql57.gha.local
        volumes:
            - "db_data:/var/lib/mysql"
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=${DB_DATABASE:-public}
            - MYSQL_USER=${DB_USERNAME:-public}
            - MYSQL_PASSWORD=${DB_PASSWORD:-public}

    php-7.4-nginx:
        build: ./docker/nginx
        dns_search: gha.local
        hostname: 7.4.gha.local
        domainname: gha.local
        restart: on-failure:2
        working_dir: /var/www/html
        ports:
            - "${APP_HTTP_FRONT_PORT:-8085}:80"
        depends_on:
            - mysql57
        volumes:
            - "./:/var/www/html"
        networks:
            gha:
                aliases:
                    - 7.4.gha.local
    redis:
        hostname: redis
        image: 'redis:latest'
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
        networks:
            gha:
                aliases:
                    - redis.gha.local

volumes:
    db_data:
        driver: local

networks:
    gha:
        driver: bridge
